---
title: "Plot Figures"
author: "Sihan Chen, Richard Futrell, Kyle Mahowald"
date: '2022-09-25'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(ggrepel)
library(RColorBrewer)
library(ggnewscale)
library(latex2exp)
library(gridExtra)
library(ggrepel)
```

Insert descriptions here I guess

Parameters:
```{r}
# decay parameter
mu <- 0.2
# P/G/S coordinates
pgs <- '0.0_-0.789_1.316'
# number of distal levels
num_dists <- 'num_dists_3'
```

Load datasheets generated by run_ib_new.py
```{r}
# output file 
d = read.csv(paste0('sheets/merge_d1d2.csv_mu_',toString(mu),'_pgs', pgs, num_dists, '.csv'))  %>%
  mutate(Language = gsub('\\[(.*?)\\]', '', Language)) %>% pivot_longer(2:10, names_to = 'mode', values_to = 'word') %>%
  separate(mode, into = c('distal_level', 'orientation'), sep = '_') %>% group_by(Language) %>% 
  mutate(word = as.character(word) %>% factor(levels = unique(.)) %>% as.numeric()) %>% ungroup() %>%
  unite('mode', c('distal_level', 'orientation'), sep = '_') %>%
  pivot_wider(names_from = mode, values_from = word)

# non-deterministic optimal frontier
curve_non_deter = read.csv(paste0('sheets/merge_d1d2.csv_mu_',toString(mu),'_pgs', pgs, num_dists, '_ib_curve.csv'))

# get columns indicating the (distal_level, orientation) combinations
co <- which(!is.na(str_extract(colnames(d), 'D\\d_')))

# calculate number of words 
d[, "nwords"] <- apply(d[,co], 1, max)

# color patelle for plotting
colourCount = 9
getPalette = colorRampPalette(brewer.pal(9, "Set1"))

```

Information plane after merging distance levels D1 and D2 (Figure 14)

```{r}
pos <- position_jitter(height = 0.01, width = 0.01, seed = 2)
ggplot(d %>% filter(LangCategory == 'real')) +
  geom_point(data = d %>% filter(LangCategory == 'simulated'), aes(x=`I.M.W.`, y=`I.U.W.`), alpha = 0.1, size = 3, color = 'gray') +
  geom_jitter(aes(x=`I.M.W.`, y=`I.U.W.`, color = Area), size = 3, position = pos) +
  geom_line(data = curve_non_deter, aes(x = complexity, y = informativity ), color = 'black', size = 1) +
  geom_smooth(data = d %>% filter(LangCategory == 'simulated'), aes(x=`I.M.W.`, y=`I.U.W.`), method = 'lm', color ='blue', 
              linetype='dashed') +
  theme_bw(25) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  xlab('Complexity') +
  ylab('Informativity') +
  xlim(0,max(d$I.M.W.) + 0.35) +
  ylim(0,max(d$I.U.W.) + 0.10) +
  scale_color_brewer(palette = 'Set2') +
  geom_text_repel(data = d %>% filter(Language %in% c('Abau (Sepik, Upper) ',
                                                      '  Doromu-Koki (Trans-New Guinea, Manubaran) ',
                                                      'Balese (Central Sudanic)')),
                  aes(x = I.M.W., y = I.U.W., label = Language),
                  point.padding = 0.1,
                  nudge_x = -0.05,
                  nudge_y = -0.05,
                  segment.curvature = -1e-20,
                  arrow = arrow(length = unit(0.015, "npc")),
                  #position = pos
  )+
  geom_text_repel(data = d %>% filter(Language %in% c('  Dyirbal (Pama-Nyungan)',
                                                      '  Kodiak Alutiiq (Eskimo-Aleut, Aleut) ',
                                                      'Hmong Njua (Hmong-Mien, Chuanqiandian)',
                                                      'English (Indo-European, Germanic)'
                                                      )),
                  aes(x = I.M.W., y = I.U.W., label = Language),
                  point.padding = 0.1,
                  nudge_x = -0.05,
                  nudge_y = 0.05,
                  segment.curvature = -1e-20,
                  arrow = arrow(length = unit(0.015, "npc"))
  )+
  ggtitle('')

ggsave(paste0('figures/orig_figures/Figure 14.png'), width = 15.3, height = 9, units = 'in')

```


